### ISSUE TITLE
Difference to helm-ucs

### ISSUE THREAD

**Issue by tmalsburg** [shosti/helm-unicode#2]
This seems similar to [helm-ucs](https://github.com/emacs-helm/helm/blob/master/helm-font.el) which is part of helm.  It would be helpful if you could explain the differences in the commentary section that is displayed in MELPA.  Thanks!

**Comment by shosti** [comment]
Oops, I didn't actually know about helm-ucs, otherwise I probably wouldn't have made this. But from poking around, helm-ucs seems unusably slow (on Mac), while helm-unicode is merely very slow :wink:. This is really just a toy package so I don't think over-explaining things is necessary.
